<?php
$form = $this->form;


$form->setAttribute('action', $this->url('auth', array('controller' => 'auth', 'action' => 'index')));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-signin');
$form->setAttribute('role', 'form');
$form->prepare(); ?>
<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4 well" style="text-align: center">
<?php

echo $this->form()->openTag($form); ?>
<p>
    <h2 class="form-signin-heading">Login forma</h2>
<?php
 if(isset($this->messages)){
    echo $this->escapeHtml($this->messages);
}
echo $this->formRow($form->get('username'));
?>
</p>
<p>
<?php
echo $this->formRow($form->get('password'));
?>
</p>
<p>
<?php
echo $this->formSubmit($form->get('submit'));

?>
</p>
<?php
echo $this->form()->closeTag();


?>
    </div>
    <div class="col-md-4"></div>
</div>