<?php
$form = $this->form;


$form->setAttribute('users', $this->url('users', array('controller' => 'users', 'action' => 'changePassword')));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-signin');
$form->setAttribute('role', 'form');
$form->prepare(); ?>
<div class="row well">
   
    <div class="col-md-6 ">
<?php

echo $this->form()->openTag($form); ?>
<p>
    <h2 class="form-signin-heading">Promeni password</h2>

</p>
<p>
<?php echo $this->formRow($form->get('password')); ?>
</p>
<p>
<?php echo $this->formRow($form->get('confirm_password')); ?>
</p>




    </div>

	</div>
<div class="row well">
		<div class="col-md 4"></div>
		<div class="col-md 4"><?php echo $this->formRow($form->get('captcha')); 
		echo $this->formHidden($form->get('secret'));?></div>
		<div class="col-md 4"></div>
	
	</div> 
	<div class="row well">
	<div class="col-md-12" style="text-align:center;">
	<p>
<?php echo $this->formRow($form->get('submit')); ?>
 &nbsp; <input type="reset" value="Reset" class="btn btn-warning btn-md" />
</p>

	<?php
echo $this->form()->closeTag();


?>
</div>
</div>