<?php
$this->headTitle('Zaboravljen password');
$this->headMeta()->appendName('description', 'Ukoliko ste zaboravili password, mozete ga resetovati kroz ovaj formular');
$form = $this->form;


$form->setAttribute('action', $this->url('users/default', array('controller' => 'users', 'action' => 'forgotenPassword')));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-signin');
$form->setAttribute('role', 'form');
$form->prepare(); ?>
<div class="row well">
 <div class="col-md-4"></div>  
    <div class="col-md-4 ">
<?php

echo $this->form()->openTag($form); ?>
<p>
    <h2 class="form-signin-heading">Reset passworda</h2>
<?php

echo $this->formRow($form->get('email'));
?>
</p>



	</div>
	</div>
<div class="col-md-4"></div>  
	<div class="row well">
		<div class="col-md 4"></div>
		<div class="col-md 4"><?php echo $this->formRow($form->get('captcha')); 
		echo $this->formHidden($form->get('secret'));?></div>
		<div class="col-md 4"></div>
	
	</div> 
	<div class="row well">
	<div class="col-md-12" style="text-align:center;">
	<p>
<?php echo $this->formRow($form->get('submit')); ?>
 &nbsp; <input type="reset" value="Reset" class="btn btn-warning btn-md" />
</p>

	<?php
echo $this->form()->closeTag();


?>
</div>
</div>